/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux yangds-Vostro-5560 3.19.0-25-generic x86_64"
#define LGL_COMPILED "Thu May 19 00:03:53 CST 2016"
#define LGL_RELEASED "Mon Nov  9 11:04:59 CET 2015"
#define LGL_VERSION "bal"
#define LGL_ID "2293bef0a4bd680210f6f5a453efa8b0a26f53ee"
